# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(help_text='Enter conference name', max_length=256)),
                ('level', models.CharField(choices=[('0', 'unknown'), ('1', 'local'), ('2', 'regional'), ('3', 'national'), ('4', 'international')], default=0, help_text='What type of Conference is this?', max_length=1)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the Registration Fee', max_digits=8)),
                ('venue', models.CharField(blank=True, help_text='Location of the event', max_length=256)),
                ('poster', models.FileField(blank=True, help_text='Upload the PDF/DOCX Poster here (ZIP/RAR format)', upload_to='%Y/%m/%d/')),
                ('start_date', models.DateField(default=datetime.datetime(2017, 4, 17, 5, 50, 43, 409983, tzinfo=utc), verbose_name='Date Started')),
                ('end_date', models.DateField(default=datetime.datetime(2017, 4, 19, 5, 50, 43, 410983, tzinfo=utc), verbose_name='Date Ended')),
                ('abstract_deadline', models.DateField(default=datetime.datetime(2017, 4, 2, 5, 50, 43, 410983, tzinfo=utc), verbose_name='Deadline of Abstract Submission')),
                ('paper_deadline', models.DateField(default=datetime.datetime(2017, 4, 7, 5, 50, 43, 410983, tzinfo=utc), verbose_name='Deadline of Paper Submission')),
                ('contact_details', models.TextField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.TextField(max_length=256, unique=True)),
                ('shortname', models.CharField(blank=True, help_text='Shortname', max_length=10)),
                ('email', models.EmailField(blank=True, help_text='Enter the official email address of the agency', max_length=254)),
                ('website', models.CharField(blank=True, help_text='Enter the website of this Agency/Organizer/Sponsor', max_length=128)),
                ('contact', models.CharField(blank=True, help_text='Enter Contact Numbers (separated with comma)', max_length=128)),
            ],
            options={
                'ordering': ('fullname',),
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers',
            field=models.ManyToManyField(null=True, to='conferences.Organizer', verbose_name='List of Organizers'),
        ),
    ]
