# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0006_auto_20170321_1516"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"ordering": ("title",), "verbose_name_plural": "Studies"},
        ),
        migrations.AlterField(
            model_name="conference",
            name="abstract_deadline",
            field=models.DateField(
                default=datetime.datetime(2017, 4, 5, 7, 24, 58, 742121, tzinfo=utc),
                verbose_name="Deadline of Abstract Submission",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2017, 4, 22, 7, 24, 58, 742121, tzinfo=utc),
                verbose_name="Date Ended",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="paper_deadline",
            field=models.DateField(
                default=datetime.datetime(2017, 4, 10, 7, 24, 58, 743121, tzinfo=utc),
                verbose_name="Deadline of Paper Submission",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2017, 4, 20, 7, 24, 58, 742121, tzinfo=utc),
                verbose_name="Date Started",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="authors",
            field=models.ManyToManyField(
                null=True, to="conferences.Author", verbose_name="List of authors"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="conferences.Conference",
                verbose_name="Conference Title",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="presentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="conferences.Author",
                verbose_name="Presented by",
            ),
        ),
    ]
