# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20170321_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='abstract_deadline',
            field=models.DateField(default=datetime.datetime(2017, 4, 5, 8, 13, 58, 70241, tzinfo=utc), verbose_name='Deadline of Abstract Submission'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 22, 8, 13, 58, 69241, tzinfo=utc), verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='paper_deadline',
            field=models.DateField(default=datetime.datetime(2017, 4, 10, 8, 13, 58, 70241, tzinfo=utc), verbose_name='Deadline of Paper Submission'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 8, 13, 58, 69241, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
